blank_issues_enabled: false

contact_links:
  - name: バグか仕様か不明な場合
    url: ../../discussions/new
    about: まず再現条件の切り分けを一緒にやりましょう

  - name: 新機能の提案（Feature要望）
    url: ../../discussions/new?category=ideas
    about: 仕様固めはここで合意してからIssue化

  - name: セキュリティ連絡先
    url: ../../security/policy
    about: 脆弱性の疑いは公開Issueにしないでください

  - name: ドキュメント一式
    url: ../../#readme
    about: README / docs/ERD.md / ASSETS_LICENSE.md など
